name: grimorio_mvc_flutter
description: "A new Flutter project."

publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.2.8+4
  flutter_svg: ^2.0.7
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/star_icon.svg
    - assets/images/alternative_star_icon.svg
    - assets/images/background.svg
    - assets/images/logo.svg
    - assets/images/grimorio.png
    - assets/images/more_stars.svg
    - assets/images/grimorio_empty.svg

  fonts:
    - family: Bigelow Rules
      fonts:
        - asset: assets/fonts/BigelowRules-Regular.ttf
